[tool.poetry]
name = "nix.dev"
version = "0.1.0"
description = ""
authors = ["Domen Kožar <domen@dev.si>"]
license = "CC BY-SA"

[tool.poetry.dependencies]
python = "^3.9"

livereload = "*"
myst-parser = {version = "*", extras = ["linkify"]}
pexpect = "*"
sphinx = "*"
sphinx-book-theme = "*"
sphinx-copybutton = "*"

[tool.poetry.dev-dependencies]
black = "==22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
